development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: rpress_development
  pool: 5
  username: rpress
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: rpress_test
  pool: 5
  username: rpress
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: rpress_production
  pool: 5
  username: rpress
  password: 
  socket: /opt/local/var/run/mysql5/mysqld.sock
